version: '3'
services:
  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./back
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy # Esperar a que el servicio MySQL esté saludable
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: bhernandez201700672
      MYSQL_DATABASE: bhernandez201700672
      MYSQL_USER: bhernandez201700672
      MYSQL_PASSWORD: bhernandez201700672
    volumes:
      - ./bhernandez201700672.sql:/docker-entrypoint-initdb.d/bhernandez201700672.sql
    ports:
      - "3306:3306"
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=bhernandez201700672 --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
